project_id = "uoyvgkfodtbauqqtbdwz"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.telegram-auth]
verify_jwt = false

[functions.telegram-generate-code]
verify_jwt = false

[functions.telegram-verify-code]
verify_jwt = false

[functions.telegram-bot-webhook]
verify_jwt = false

[functions.telegram-miniapp-auth]
verify_jwt = false

[functions.partner-scan-qr]
verify_jwt = false

[functions.expire-subscriptions]
verify_jwt = false
