project_id = "uoyvgkfodtbauqqtbdwz"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.telegram-auth]
verify_jwt = false

[functions.telegram-generate-code]
verify_jwt = false

[functions.telegram-verify-code]
verify_jwt = false

[functions.telegram-bot-webhook]
verify_jwt = false
